### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by rom1504** [andrewrk/mineflayer#203]
Currently mineflayer has very little tests and lot of functionalities. In order to figure out what works and what doesn't in order to fix the problem, it's needed to test manually the examples which is not very efficient.

It would be nice to have a way to test various functionalities present in the examples automatically, for example : 
* reading the username and message in the chat
* writing in the chat
* knowing what blocks are around the bot
* digging a block
* ...

I think a good way of testing all this would be to assume a minecraft server is running at a given host and port and test whether : 
* it's crashing : that's basic but really a lot of things crash currently so that would be useful
* it works : by checking the state of mineflayer structures (for example checking the usernames are not undefined, that the blocks are not undefined, that a bot has indeed changed after digging that block)

Testing all the functionalities is a big thing to do, but having a simple framework for adding test and adding a test after something has been fixed would be nice.

I think the end results of this testing would be a generated list of what works and what doesn't, so it would be easier to contribute.

Tell me what you think :)

**Comment by roblabla** [comment]
We should ensure two things : 

1. Internal consistency. For this, we should unit test functions with values we assume correct.
2. External consistency. For this, we could either write a simple node-mc-proto server implementing the functionality required for the test, and make sure everything works properly.

I'm sort of against using a minecraft server for this, since node-minecraft-protocol is already supposed to be battle-tested as far as the protocol is concerned.

**Comment by rom1504** [comment]
The problem with "writing a simple node-mc-proto server implementing the functionality required for the test" is mineflayer is high level, so a simple action mineflayer-wise might mean a lot of different part involved server wise. Would it really be possible to test significant things without having to implement the whole minecraft server ?

node-minecraft-protocol is tested protocol wise, but it is not tested about the higher level things mineflayer provide, for example parsing of the chunk, handling the chat messages, ...

But I agree it might be better not to use a minecraft server, it would make the test faster. If it can be done, that would be nice.

**Comment by Corgano** [comment]
I'm thinking the exact opposite, the best idea is to use the notchian server. The reasoning for this is we don't write mineflayer or node-minecraft-protocol to be compatible with itself, we write it to be compatible with minecraft. Testing mineflayer on our custom built server is pointless because this is not where mineflayer will be used in the real world.

Ideally we should set up a map file with a set of chests, containers, blocks, items, etc, designed to test our bot. The map file can easily be brought onto later server versions to test without needing to re-write a testing server, and we would know how the bot interacts with this test will reflect the way the bot responds to real world servers.

**Comment by roblabla** [comment]
The big problem with using a minecraft server as a test bed is that it's completely unreliable. I had to entirely _remove_ the timeouts from node-minecraft-protocol's test (well, actually, I made the timeouts something like 40 minutes) because minecraft_server could take up to 10 minutes to start, accept connections, log a player in, etc...

There is a lot we can test without having to do too much work. Chunk loading, inventory management, physics, etc... can all be tested very reliably with a simple node-minecraft-protocol server. More complicated behaviors might need a real minecraft_server, but I def think we should implement as much as possible without it.

**Comment by thejoshwolfe** [comment]
I'd like to propose a different approach, which is having much of the testing automated, but not all of it.

I'm imagining you would spin up a server manually, and log yourself in with the notchian client, mostly to babysit the test in case something crazy happens during testing. Then you run the test bot, which tries to do everything it can in a long sequence. (This is almost exactly the process I just followed to test all the functions in the chatterbox example.)

The bot will probably need to be an op in order to give itself the items it needs to do the testing (pistons, enchanting table, etc.). The test sequence might be something like this:

 * using bare hands, dig down 1m, and then dig an area around it to give itself a workspace. (this tests digging and dirt entities spawning and getting collected.)
 * use /give to get stone, dirt, gravel, and place them in a specific configuration beside itself. (this tests placing blocks.)
 * use various tools (again using /give) to test that it can harvest cobblestone with the right tool, etc. (this tests equipping tools.)
 * test to make sure it sees gravel fall when it digs out the block below it.
 * place a piston and a lever, operate the lever, make sure we're getting the `pistonMove` event.
 * place a chest, put items in it, close the chest, open it, pull items out, etc. (this is currently broken).
 * announce in chat that the bot is testing punching, and then punch the human babysitter.
 * ...

This plan seems fairly easy to program, and low enough effort to run the tests that if someone wants to know if everything's working (which I currently do), it's fairly easy to get an answer quickly. (Granted it's not as easy as a fully-automated test.) I'm imagining a successful test run would take less than a minute, and painless enough that developers want to run it before pushing their commits.

This proposal has an answer to the problem of trying to have reproducible tests in an inherently random game, which is the human babysitter. For example, if the bot spawns on the edge of a lake, and doesn't know how to dig itself into a suitable testing workspace, the human can identify the problem, and fix it in various ways: leading the bot away from the water, placing dirt around the bot, rerolling the world, etc. This is obviously suboptimal, but hopefully human intervention will rarely be required, making the testing worthwhile.

I didn't quite understand all the server proposals in this thread so far, but I think writing our own server is no good, because we really need to test our interaction with the real server. I think that maintaining a controlled test world is a decent idea, but I think it would be harder to maintain than a bot that creates a controlled test environment as I described above.

Obviously, this proposal is all talk for now. Let the most enthusiastic developer win!

**Comment by rom1504** [comment]
I like that idea. This would test "real world" problems in a semi-automatic way.
We may want to also have some totally automatic tests (like this https://github.com/andrewrk/mineflayer/blob/master/test/test.js) but this semi-automatic way would probably be much faster than manually booting all the .js in examples/ , calling the commands manually, figuring out if it really worked, etc.

I think it would be nice to start with a simple one of these tests, to be able to add other ones more easily later.

**Comment by roblabla** [comment]
Right, so having something akin to a "test" example that uses every functionality of mineflayer to make sure they work ? That actually sounds reasonable enough. We'll still need lots more of specs in the fully-automated and server-independent testing though.

**Comment by andrewrk** [comment]
Small idea for the bootstrapping process: instead of the first action being digging, first action could be giving itself 999 dirt and then jump-building a platform in the sky to test. the sky is pretty uniform

**Comment by thejoshwolfe** [comment]
> the sky is pretty uniform

That's a good idea.

Also, instead of punching the human spectator, the test script could log in multiple bots (duh). That way, we can also test watching people die, disconnect, etc. without human involvement. (watching someone disconnect is currently broken.)

**Comment by thejoshwolfe** [comment]
Even better idea, test in a superflat world. here are some `server.properties` settings that got me a completely deterministic world (as far as I can tell):

```properties
level-type=FLAT
generate-structures=false
spawn-monsters=false
spawn-animals=false
spawn-npcs=false
```

**Comment by thejoshwolfe** [comment]
> some server.properties settings

Unfortunately, these are only useful if #233 is implemented, as many of these settings are missing from the "Open to LAN" strategy. For example, I can't figure out how to turn off monster spawning.

**Comment by thejoshwolfe** [comment]
> how to turn off monster spawning

Ok, I figured it out, but it's dumb. You have to start playing, and then as quickly as you can type `/gamemode doMobSpawning false` in the chat box (while the world is running, mind you), and that prevents any more monsters from spawning. Then you run around with a diamond sword killing all the slimes and sheep that spawned while you were typing that, and then your world is ready for testing.

**Comment by roblabla** [comment]
you could just change gamemode to peaceful. that kills the mobs.

**Comment by rom1504** [comment]
@thejoshwolfe What's your progress on your superflat.js ? Does it need a lot of supervision or could it be fully automated ?

**Comment by thejoshwolfe** [comment]
it doesn't need supervision at the moment. it needs a server running where it can use cheatcodes as the username "bot". preferably, the world should be superflat with mob spawning disabled, but that isn't strictly necessary.

the test run takes about 3 seconds from start to finish, but of course that's only with some testing implemented.

**Comment by rom1504** [comment]
I wonder if we could automate it and add it to circle ci, just like https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/test/test.js.

It would be nice to be able to know whether a commit breaks such and such stuff without having to do anything.

**Comment by rom1504** [comment]
So I added information about the tests there https://github.com/andrewrk/mineflayer/blob/master/doc/contribute.md#creating-tests

Some tests are already implemented, more test can be done following the instruction the contribute.md.

I think we can create new issues for new tests, small issues are easier to handle than fat issues like this (which are sometimes still good to start with, to talk)
