### ISSUE TITLE
Code style : unneeded comma

### ISSUE THREAD

**Issue by rom1504** [andrewrk/mineflayer#226]
At the end of many arrays and objets there are comma like in this example : 
```js
bot.client.write('close_window', {
      windowId: window.id,
    });
```

Is there a reason for this ?

**Comment by deathcap** [comment]
New properties and elements can be added on subsequent lines without changing the prior line to add a comma (= cleaner diff)

**Comment by demipixel** [comment]
As deathcap said, I really like this method because it allows you to easily add new properties...

... but, it's technically not "clean" coding. Especially because trying this kind of thing in JSON will make it crash. It's pretty much a matter of opinion. For a more official / widespread project, it might be smarter to remove them to avoid any trouble, but then again, it doesn't really matter.

**Comment by rom1504** [comment]
I'm ok with that reason, I'll just have to figure out how to explain WebStorm that's it's ok.

**Comment by rom1504** [comment]
Actually, yeah this might make the commits diff slightly better.
But it makes the actual code you look at uglier.
So I still think removing these comma is better.

**Comment by thejoshwolfe** [comment]
> But it makes the actual code you look at uglier.

I disagree; I think the line-to-line consistency is prettier.

But aesthetics will always be a matter of opinion, so I think we should defer to the functionality advantages of terminating lines with commas. If all the lines are syntactically interchangeable, diffs are tidier, and reordering lines is easier. Over the last few years of maintaining dependency lists in package.json files, I've been burned by the necessary comma inconsistency at least 5 times. (I would add a line and forget to add a comma to the previous line, or I would reorder lines and forget to move the commas around independently.) This frustration is one of the motivations for https://github.com/andrewrk/liblaxjson .

On a similar note, I'd like to discuss this style:

```js
var vec3 = require('vec3')
  , assert = require('assert')
  , zlib = require('zlib')
```

My opinion is that this looks terrible. But opinions aside, this also seems functionally deficient, because the first line is different from the others. An independent problem is that the last line is missing a semicolon, which is technically not a problem, but it's a bit scary to rely on semicolon insertion.

I propose this syntax instead:

```js
var vec3 = require('vec3');
var assert = require('assert');
var zlib = require('zlib');
```

This syntax is super normal, easy, consistent, etc. Why would anyone do anything else?

**Comment by rom1504** [comment]
I agree with your second point.

I'm afraid I can't agree with your first point though.
To me this : 
```js
{
  'a':'b',
  'c':'d',
  'e':'f',
}
```
is the same as `{'a':'b', 'c':'d','e':'f',}`.

It would also mean we would write stuff like `[3,4,]` (with line breaks), I just don't like it, it doesn't make sense.

Javascript accepts this yes, but I don't think using it is a good thing.

It also doesn't seem very standard in node.js. For example this https://github.com/feross/standard doesn't allow for additional comma.

**Comment by rom1504** [comment]
Also, looks what happens when mojang mess with json https://github.com/andrewrk/mineflayer/blob/master/lib/chat_message.js#L122

**Comment by rom1504** [comment]
Oh well, the recently released last version of webstorm (https://youtrack.jetbrains.com/issue/WEB-3538#tab=History) apparently is ok with that. If it stops saying all lines with a trailing comma are an error, I might make do with that convention...

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/protocol.js 
node-minecraft-protocol doesn't have these trailing comma.

**Comment by rom1504** [comment]
So, indeed WebStorms 10 allows to not error on these trailing comma.
I guess it doesn't matter that much.
