### ISSUE TITLE
mob/player armor/enchantments detection? 

### ISSUE THREAD

**Issue by pokeball99** [andrewrk/mineflayer#259]
can mineflayer detect the armor and enchantments of mobs and players?

**Comment by demipixel** [comment]
I don't know if this is true, but I'm pretty sure we can only see the enchant effect, not the actual effect itself.

**Comment by rom1504** [comment]
I'm not sure where this would be stored protocol-wise, maybe in the metadata ? (see #249 )

**Comment by roblabla** [comment]
Yup, metadata.

**Comment by rom1504** [comment]
I added an example on how to know the held items of a player in https://github.com/andrewrk/mineflayer/blob/78485bbafea1c3eecef5221fd63014a079885c19/examples/chatterbox.js#L79
Also see https://github.com/andrewrk/mineflayer/blob/master/doc/api.md#entityequipment5

In order to know the enchantment of an item, you'll have to console.log the nbt.
