### ISSUE TITLE
Just a random repo,don't know if it could be of any use

### ISSUE THREAD

**Issue by pokeball99** [andrewrk/mineflayer#267]
https://github.com/nickolanack/node-minecraft-agent

**Comment by rom1504** [comment]
So that's basically a not so well organized "mineflayer alternative" using a node-minecraft-protocol updated at the time but not up to date now (why not PR?).

I don't think there's much code in there that can be useful to mineflayer, @nickolanack ( https://github.com/nickolanack/node-minecraft-agent/issues/1 ) might want to participate (or use) mineflayer though !

**Comment by nickolanack** [comment]
definitely unorganized, what is PR?

**Comment by roblabla** [comment]
Repository was deleted :(

**Comment by demipixel** [comment]
RIP

**Comment by roblabla** [comment]
https://github.com/nickolanack/node-mc-agent going back up.
