### ISSUE TITLE
Parse the JSON received on 'message' event.

### ISSUE THREAD

**Issue by AlexKvazos** [andrewrk/mineflayer#273]
Hello, I'd like to know the best way of parsing the JSON that arrives in the 'message' event. Thanks!

**Comment by demipixel** [comment]
I would recommend using on 'chat' or on 'whisper'. If you need something else for a server with custom messages, you're going to need to write your own parser. If you don't care about colors, you can just try doing "json.toString()" to get the string of text. From that, you'll be able to use regex. Otherwise, you'll need to know exactly what each time of message contains so you can parse it manually.

If you have more questions, visit us in the gitter! (Link in the README)

**Comment by AlexKvazos** [comment]
Listening to the chat event didn't help because It was not getting emitted. Probably because I joined a 1.8.1 server with a 1.8.3 protocol. But yeah, I already wrote a parser myself to color the chat with html span tags. Thanks!

**Comment by roblabla** [comment]
1.8.1 and 1.8.3 protocols are the same ^^.

**Comment by rom1504** [comment]
Likely due to a non vanilla server as usual.
